-- local wilder = require('wilder')
-- wilder.setup({
--   modes = {':', '/', '?'},
--   next_key = '<Tab>',
--   previouw_key = '<S-Tab>',
--   enable_cmdline_enter = 0,
-- })
-- 
-- wilder.set_option('pipeline', {
--   wilder.branch(
--     wilder.cmdline_pipeline(),
--     wilder.search_pipeline()
--   ),
-- })
-- 
-- wilder.set_option('renderer', wilder.popupmenu_renderer({
--   pumblend = 20, -- transparency
--   -- highlighter applies highlighting to the candidates
--   highlighter = wilder.basic_highlighter(),
-- }))
-- 
-- wilder.popupmenu_border_theme({
--   highlights = {
--     border = 'Normal', -- highlight to use for the border
--   },
--   -- 'single', 'double', 'rounded' or 'solid'
--   -- can also be a list of 8 characters, see :h wilder#popupmenu_border_theme() for more details
--   border = 'rounded',
-- })
