set-option global scrolloff 5,1
set-option global grepcmd 'rg --column'

add-highlighter global/ number-lines -hlcursor -relative

# Plugin stuff from now on
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "kakoune-lsp/kakoune-lsp" do %{
    cargo install --locked --force --path .
}

plug "andreyorst/fzf.kak" config %{
  map global normal <c-p> ': fzf-mode<ret>'
}
